# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/arubaslim/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/arubaslim/proprietary/lib/hw/camera.msm7627a.so:system/lib/hw/camera.msm7627a.so \
    vendor/samsung/arubaslim/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/samsung/arubaslim/proprietary/lib/libarccamera.so:system/lib/libarccamera.so \
    vendor/samsung/arubaslim/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/samsung/arubaslim/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/arubaslim/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/samsung/arubaslim/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/samsung/arubaslim/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/samsung/arubaslim/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/samsung/arubaslim/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/arubaslim/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/samsung/arubaslim/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/samsung/arubaslim/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/samsung/arubaslim/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/samsung/arubaslim/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/samsung/arubaslim/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxAc3HwDec.so:system/lib/libOmxAc3HwDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxIttiamVenc.so:system/lib/libOmxIttiamVenc.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/samsung/arubaslim/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/samsung/arubaslim/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/samsung/arubaslim/proprietary/lib/libPanoraMax3.so:system/lib/libPanoraMax3.so \
    vendor/samsung/arubaslim/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/samsung/arubaslim/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/samsung/arubaslim/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/samsung/arubaslim/proprietary/bin/sec-ril:system/bin/sec-ril \
    vendor/samsung/arubaslim/proprietary/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
    vendor/samsung/arubaslim/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/samsung/arubaslim/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
    vendor/samsung/arubaslim/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    vendor/samsung/arubaslim/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/arubaslim/proprietary/bin/test_gemini:system/bin/test_gemini \
    vendor/samsung/arubaslim/proprietary/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \
    vendor/samsung/arubaslim/proprietary/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \
    vendor/samsung/arubaslim/proprietary/bin/mm-jpeg-enc-test-client:system/bin/mm-jpeg-enc-test-client \
    vendor/samsung/arubaslim/proprietary/bin/mm-venc-omx-test:system/bin/mm-venc-omx-test \
    vendor/samsung/arubaslim/proprietary/bin/mm-aenc-omxaac-test:system/bin/mm-aenc-omxaac-test \
    vendor/samsung/arubaslim/proprietary/bin/mm-aenc-omxqcelp13-test:system/bin/mm-aenc-omxqcelp13-test \
    vendor/samsung/arubaslim/proprietary/bin/sensord:system/bin/sensord \
    vendor/samsung/arubaslim/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/samsung/arubaslim/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/arubaslim/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/arubaslim/proprietary/bin/cnd:system/bin/cnd \
    vendor/samsung/arubaslim/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/samsung/arubaslim/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/samsung/arubaslim/proprietary/bin/bccmd:system/bin/bccmd \
    vendor/samsung/arubaslim/proprietary/bin/csr_dut:system/bin/csr_dut \
    vendor/samsung/arubaslim/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/samsung/arubaslim/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/samsung/arubaslim/proprietary/bin/p2p_supplicant:system/bin/p2p_supplicant \
    vendor/samsung/arubaslim/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin \
    vendor/samsung/arubaslim/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
    vendor/samsung/arubaslim/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin \
    vendor/samsung/arubaslim/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf
